# The versions are manually kept the same as the ones in build.mill.
[versions]
scala = "2.13.15"
upickle = "3.3.1"

[libraries]
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }
upickle = { module = "com.lihaoyi:upickle_2.13", version.ref = "upickle" }
